name: MischiefCountdowns
version: $version
author: sven@wollinger.email
main: com.mischiefsmp.countdowns.MischiefCountdowns
api-version: 1.19
website: wollinger.io
commands:
  countdown:
    description: Countdown command
    usage: "/countdown [start/stop] <id> <seconds> [pink/blue/red/green/yellow/purple/white]"
permissions:
  countdowns.create:
    default: false
  countdowns.view:
    default: true